version: '3'

services:
  db:
    image: postgres:14.3
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    container_name: teslodb
    volumes:
      - ./postgres:/var/lib/postgresql/data

      #lugar por defecto donde se guarda el contenedor: /var/lib/postgresql/data
      #si se ejecuta docker-compose up y no aparece la carpeta con la info de la bd algo esta mal en la direccion
